== Acknowledgements

A whole lot of people have been involved in making the Lost Colonies Larp into the gaming community we have today.  We would like to take a moment to thank them for their efforts:

Jason Marin, 
Marie DelRio,
Jason Feldman,
Charles Wheeler, 
Chris Stephens, 
Angela Griffin, 
Andy Randolph, 
Evin Hodges, 
Lee Gelwicks, 
Cris Picado, 
Cindy Jackson, 
Barbara Perez Marquez, 
Roy Sullivan, 
JymmeAnne Walton,
Ben Theis, 
Michelle Theis, 
Irene Glasse,
Chris Kackley,
Jean Mesic, 
Derek Jolene Kholin, 
Mark Davis, 
Kat Gray, 
Mike Gray, 
William Hannings, 
Sarah Brand, 
Kristin Keyser,
Emily Rice,
Mike Young,
Dave McCormick,
Dominic Gonzaga,
Kirk Brunstetter,
Christiana Brunstetter,
Mark Wallace


== Playtesters

The following people helped us with our playtesting efforts as well and are deserving of our thanks:

Marsaline Picado, Cris Picado, Jaelin Picado, Cindy Jackson,
Harold Martin,
JymmeAnne Walton,
David McCormick, 
Eric K. Smith, 
Chris Hom, 
Karen Fletcher,
Michael Young, 
Alexander Haus,
Nick Sekula,
Emily Rice,
Russell Kupferer,
Sarah Smith,
Thomas Hylton

== Credits and License

John Meagher designed the Lost Colonies logos, find more of John's work at talesofthelefthand.com

Cait May designed our iconic Characters, find more of Cait's work at caitmayart.com

Tara Clapper edited our Rulebooks for content and clarity, find more of Tara's work at geekinitiative.com

This work is derived from the Catalyst Open Game System version 3.5 which was graciously provided by the wonderful folks at Catalyst: The Lucid Dream Larp.  They can be found at dreamlarp.com

There are many changes from this original work.  Our use of the Catalyst Open Game System should not be construed as an endorsement by the Catalyst: The Lucid Dream

== Safety Rules Credit

There are many sources that we pulled from as we wrote our safety and community standards.  These tools were developed by the larp community and they deserve credit for their work.

* Our safety rules around Pronouns was taken from this article: https://nordiclarp.org/2017/12/01/larp-tools-pronoun-markers-correction-mechanics/  also, please visit https://shop.learnlarp.com/ to support Maury Brown, the author of the article.
* Our Lookdown rule was created by New World Magischola and we sourced it from this article: https://nordiclarp.org/2016/09/09/creating-culture-trust-safety-calibration-larp-mechanics/
* Our Safety Check Hand Signals is from Imagine Nation Collective LLC who run Dystopia Rising and other events.  Find the original article at http://www.imaginenationcollective.com/okcheckin/

Thank you very much to these accomplished teams for developing or highlighting community safety rules to help larp as a larger community become more safe and welcoming.

== Copyright

This work is produced by Torakand Adventures, LLC and is provided under license for use by the Lost Colonies Larp members and their guests. Members of Lost Colonies Larp may make copies of this work for your their personal use only. All other rights are reserved.
